### ISSUE TITLE
Problem with travis-ci

### ISSUE THREAD

**Issue by loechel** [collective/collective.messagesviewlet#2]
Hi, could you please have a look at your travis-ci config, 
the travis-ci.yml looks ok, but the generated https://travis-ci.org/collective/collective.messagesviewlet/jobs/242043213/config 
did include something that keeps the build rund for several hours / forever.

I have canceled the build as all other Plone Projects were lined up and did not run, because not worker get freed.

**Comment by bsuttor** [comment]
Hi,

[This commit](https://github.com/collective/collective.messagesviewlet/commit/17032df0263f56d228b0ade1acbfc0b3917666bb) resolved this issue, so I close it.
